version: '3'

services:
  valuematrixbackend:
    container_name: valuematrixbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    restart: 'on-failure'

    volumes:
      - ./valuematrixbackend
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisorvaluematrix
    restart: 'always'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
     
      - /etc/machine-id:/etc/machine-id:ro

    devices:
      - /dev/kmsg:/dev/kmsg
    depends_on:
      - valuematrixbackend
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheusvaluematrix
    restart: 'always'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
     
      - /etc/machine-id:/etc/machine-id:ro

    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
    
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    container_name: grafanavaluematrix
    restart: 'always'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./grafana/grafana.ini:/etc/grafana/graphana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/data:/var/lib/grafana

    

    depends_on:
      - prometheus
    ports:
      - "3001:3001"
    
